## Data Science Life Cycle
- Involves 6-7 steps
- 1.Bussiness training
- 2.Data preparation
- 3.data munging
- feature selection
      - EDA tool
- 4.model raining
- 5.model evalution
- 6.model deployment
       - aws
       - IBM waston studio
 - 7.model tracking

## data analysis libraries
- Numpy
- Pandas
- Matplotlib
- Seaborn

## numpy
- numerical python
- developed in 2005 by Travis Oliphat
- numpy is 50 times faster of lists
- create arrays
   - zero dimension array
   - single dimensional array
   - two dimenesional arryas
   - muti dimentional arrays
   
- linear algebra ,Fourier Transformer, matrices
   


In [3]:
import numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
np.__version__

'1.16.4'

## creating array's

In [7]:
import numpy as np
x=np.array(23)
print(x)

23


In [8]:
##check dimension
np.ndim(x)

0

In [9]:

##1-d array
x1=np.array([12,23,4,5,6])
print(x1)
print(np.ndim(x))

[12 23  4  5  6]
0


In [11]:
## 2-d array
x2=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) ##same lenght should be present
print(x2)
print("dimensions are:"np.ndim(x2))

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
2


In [12]:
## to check the number of elements
np.size(x2)

12

In [13]:
## to get the rows and columns
np.shape(x2)

(2, 6)

## 3-D array
- ([[[]]])

In [15]:
import numpy as np
x3=np.array([[[1,2,3],[4,5,6],[8,9,6]]])
print(x3)
print(np.ndim(x3))
print(np.size(x3))
print(np.shape(x3))

[[[1 2 3]
  [4 5 6]
  [8 9 6]]]
3
9
(1, 3, 3)


## methods to create arrays
- Zeros
- Ones
- linspace
- logspace
- arrange


In [17]:
a0=np.zeros(2,dtype=int)
a0


array([0, 0])

In [18]:
a1=np.ones(5,dtype=int)
a1

array([1, 1, 1, 1, 1])

In [21]:
a1=np.ones(5,dtype=int)
print(a1)
a2=a1.reshape(5,1)
print("reshape of a1 to a2",a2)
a3=a1.reshape(1,5)
print("reshape of a1 to a3",a3)

[1 1 1 1 1]
reshape of a1 to a2 [[1]
 [1]
 [1]
 [1]
 [1]]
reshape of a1 to a3 [[1 1 1 1 1]]


In [9]:

a=np.arange(1,12,2)
print(a)
print(np.ndim(a))
print(np.size(a))


[ 1  3  5  7  9 11]
1
6


##  Possibilities to reshape 6 elements
- (2,3)
- (3,2)
- (6,1)
- (1,6)

In [10]:
a1=a.reshape(2,3)
print(a1)

[[ 1  3  5]
 [ 7  9 11]]


In [12]:
l1=np.logspace(1,5,3)
print(l1)

[1.e+01 1.e+03 1.e+05]


In [13]:
l2=np.linspace(1,5,3)
print(l2)

[1. 3. 5.]


In [15]:
r=np.random.rand(3,2) #prints the floating values
print(r)

[[0.50476024 0.37941836]
 [0.50793497 0.9109888 ]
 [0.03911492 0.50598343]]


In [16]:
r1=np.random.randint(1,5)
r1

1

In [17]:
r2=np.random.randn(1,10)
print(r2)

[[ 0.32424465 -0.55719696  0.22562282 -1.55394166 -0.08188729 -0.27722098
   0.92285493 -1.3823162   0.63036812  1.25114891]]


In [18]:
np.ndim(r2)

2

In [20]:
r3=r2.flatten()
r3

array([ 0.32424465, -0.55719696,  0.22562282, -1.55394166, -0.08188729,
       -0.27722098,  0.92285493, -1.3823162 ,  0.63036812,  1.25114891])

In [21]:
np.ndim(r3)

1

## accessing elements
1. indexing
     - +ve
     - -ve
2. slicing
     -[strat:stop:step]
3. loop
    -for
    -while
